let translate = [
    { text: `answer`, uz: `javob` },
    { text: `black`, uz: `qora` },
    { text: `car`, uz: `mashina` },
    { text: `camera`, uz: `kamera` },
    { text: `designer`, uz: `modelyer, bezakchi rassom` },
    { text: `dark`, uz: `kulrang, qoramtir` },
    { text: `expensive`, uz: `qimmat, narxi bland` },
    { text: `exercise`, uz: `mashq` },
    { text: `end`, uz: `oxir, nihoya, yakun` },
    { text: `find`, uz: `topmoq, topib olmoq` },
    { text: `five`, uz: `besh` },
    { text: `how`, uz: `qanday` },
    { text: `hotel`, uz: `mehmonxona` },
    { text: `hand`, uz: `qo'l` },
    { text: `interesting`, uz: `qiziqarli, qiziq` },
    { text: `Italian`, uz: `italiyalik` },
    { text: `kilo`, uz: `kilo` },
    { text: `little`, uz: `unchalik yaxshi emas, kichkina` },
    { text: `London`, uz: `London` },
    { text: `lawyer`, uz: `yurist, huquqshunost` },
    { text: `make`, uz: `yasamoq` },
    { text: `new`, uz: `yangi` },
    { text: `near`, uz: `yaqin` },
    { text: `out`, uz: `... dan, tashqarida` },
    { text: `open`, uz: `ochiq` },
    { text: `office`, uz: `ofis` },
    { text: `orange`, uz: `apilsin, sariq` },
    { text: `parent`, uz: `ota` },
    { text: `parents`, uz: `ota-ona` },
    { text: `postcard`, uz: `ochiq xat, pochta` },
    { text: `post`, uz: `stolba, ustun, tirgak` },
    { text: `photograph`, uz: `fotografiya` },
    { text: `question`, uz: `savol` },
    { text: `room`, uz: `xona` },
    { text: `red`, uz: `qizil` },
    { text: `right`, uz: `to'g'ri, o'ng` },
    { text: `single`, uz: `yolg'iz` },
    { text: `shoes`, uz: `bir juft poyavzal` },
    { text: `say`, uz: `demoq, aytmoq` },
    { text: `seat`, uz: `o'rin, joy` },
    { text: `shop`, uz: `do'kon` },
    { text: `stop`, uz: `stop` },
    { text: `street`, uz: `ko'cha` },
    { text: `six`, uz: `olti` },
    { text: `skiing`, uz: `chang'i sporti` },
    { text: `time`, uz: `vaqt` },
    { text: `ten`, uz: `o'n` },
    { text: `what`, uz: `nima` },
    { text: `where`, uz: `qayerda` },
    { text: `who`, uz: `kim` },
    { text: `why`, uz: `nima uchun, nega` },
    { text: `well`, uz: `yaxshi, juda yaxshi, quduq` },
    { text: `with`, uz: `bilan` },
    { text: `word`, uz: `so'z kalima` },
    { text: `wife`, uz: `hotin, rafiqa` },
    { text: `woman`, uz: `ayol` },
    { text: `yes`, uz: `ha` },
]