let translate = [
    { text: `after`, uz: `keyin, so'nggi` },
    { text: `also`, uz: `ham, shuningdek` },
    { text: `all`, uz: `buttun, hamma, to'liq` },
    { text: `always`, uz: `hamisha, har doim` },
    { text: `away`, uz: `yo'qlikda, yo'q vaqtda` },
    { text: `arrive`, uz: `yetib kelmoq, kelmoq` },
    { text: `bank`, uz: `bank` },
    { text: `breakfast`, uz: `nonushta` },
    { text: `boil`, uz: `qaynamoq, qaynatmoq` },
    { text: `before`, uz: `oldin` },
    { text: `by`, uz: `yonida, yaqinda, atrofida` },
    { text: `cost`, uz: `narx, baho, qiymat` },
    { text: `chocolate`, uz: `shokolad` },
    { text: `clothe`, uz: `kiy(dir)moq, kiyin(tir)moq` },
    { text: `clothes`, uz: `kiyim-kechak, kiyim-bosh, libos` },
    { text: `coffee`, uz: `qahva` },
    { text: `day`, uz: `kun` },
    { text: `different`, uz: `turli, farqli, har xil, turli-tuman` },
    { text: `dirty`, uz: `iflos, kir` },
    { text: `degree`, uz: `daraja` },
    { text: `every`, uz: `har` },
    { text: `evening`, uz: `kechqurun, kechki payt` },
    { text: `earth`, uz: `yer, tuproq` },
    { text: `finish`, uz: `tugatmoq, yakun` },
    { text: `free`, uz: `bepul, tekin` },
    { text: `fly`, uz: `pashsha` },
    { text: `fruit`, uz: `meva, meva-cheva` },
    { text: `forget`, uz: `unitmoq, esdan chiqarmoq` },
    { text: `forget`, uz: `general, umumiy unvon, hammaga xos` },
    { text: `get`, uz: `olmoq, erishmoq` },
    { text: `has`, uz: `"have" fe'lining hizirgi zamon 3-shaxs birlik shakli` },
    { text: `happen`, uz: `sodir bo'lmoq, yuz bermoq` },
    { text: `hard`, uz: `qattiq, qiyin, og'ir, mashaqqatli` },
    { text: `hospital`, uz: `kasalxona, shifoxona` },
    { text: `house`, uz: `uy, bino` },
    { text: `hour`, uz: `(vaqt haqida) soat` },
    { text: `ice-cream`, uz: `musqaymoq` },
    { text: `lot`, uz: `katta miqdorda, ancha` },
    { text: `like`, uz: `yoqtirmoq, yaxshi ko'rmoq` },
    { text: `live`, uz: `yashamoq` },
    { text: `love`, uz: `sevgi` },
    { text: `language`, uz: `til` },
    { text: `money`, uz: `pul, axcha` },
    { text: `meet`, uz: `uchratmoq, uchrashmoq` },
    { text: `morning`, uz: `ertalab` },
    { text: `museum`, uz: `muzey` },
    { text: `mathematics`, uz: `matematika` },
    { text: `never`, uz: `hech qachon, aslo, sira` },
    { text: `often`, uz: `tez-tez` },
    { text: `pass`, uz: `o'tmoq, o'tib ketmoq, uzatmoq, uzatib yubormoq` },
    { text: `present`, uz: `hozir, ayni payt` },
    { text: `play`, uz: `o'yin, vaqtichog'lik` },
    { text: `parth`, uz: `kecha, bazm, o'tirish` },
    { text: `remember`, uz: `yodda tutmoq, eslamoq` },
    { text: `round`, uz: `aylana, doira` },
    { text: `simple`, uz: `oddiy, sodda, oson` },
    { text: `Scotland`, uz: `shatlandiya` },
    { text: `sometimes`, uz: `ba'zan, ba'zida` },
    { text: `speak`, uz: `gapirmoq, gaplashmoq` },
    { text: `start`, uz: `boshla(n)moq` },
    { text: `sunday`, uz: `yakshanba` },
    { text: `sentence`, uz: `gap` },
    { text: `sleep`, uz: `uyqu, uxlash` },
    { text: `seven`, uz: `yetti` },
    { text: `try`, uz: `urinish, harakat qilib ko'rish` },
    { text: `thing`, uz: `narsa, buyum; 2. mulki mol-mulk` },
    { text: `teach`, uz: `o'rgatmoq, o'qitmoq` },
    { text: `usually`, uz: `oddatga ko'ra, oddatda, ko'pincha` },
    { text: `winter`, uz: `qish` },
    { text: `weekend`, uz: `hafta oxiridagi dam` },
    { text: `water`, uz: `suv` },
    { text: `young`, uz: `yosh, juda yosh` },
]