let translate = [
    { text: `bus`, uz: `avtobus` },
    { text: `broken`, uz: `1. singan, siniq, buzuq, 2. buzilgan` },
    { text: `clock`, uz: `soat` },
    { text: `cry`, uz: `baqiriq, qichqiriq, yig'lamoq` },
    { text: `enjoy`, uz: `maza, lazzatlanmoq` },
    { text: `feeling`, uz: `his-tuyg'u, sezgi, hisiyot` },
    { text: `fine`, uz: `yaxshi` },
    { text: `film`, uz: `kino, fotoplyonka` },
    { text: `funny`, uz: `qiziq, ajib, kulgili, kulgi qistatadigan` },
    { text: `order`, uz: `tartib, saranjomlik, sarishtalik, 2. buyruq, farmoyish 3. buyurtma` },
    { text: `put`, uz: `qo'ymoq, solmoq, joylamoq, yotqizmoq` },
    { text: `running`, uz: `yugurish` },
    { text: `read`, uz: `o'qimoq` },
    { text: `rain`, uz: `yomg'ir` },
    { text: `ring`, uz: `jaranglagan ovoz` },
    { text: `run`, uz: `yugurish` },
    { text: `river`, uz: `daryo, soy, anhor` },
    { text: `study`, uz: `o'qish, o'qish-o'rganish, ilmiy tekshirish` },
    { text: `subject`, uz: `grammatikada ega` },
    { text: `see`, uz: `ko'rmoq, qaramoq` },
    { text: `sitting`, uz: `o'tirish` },
    { text: `tomorrow`, uz: `erta, ertaga, kelajakda, kelgusida` },
    { text: `umbrella`, uz: `soyabon` },
]