let translate = [
    { text: `brown`, uz: `jiggarrang, malla` },
    { text: `build`, uz: `qurmoq, yasamoq` },
    { text: `book`, uz: `kitob` },
    { text: `continuous`, uz: `davomli, uzluksiz` },
    { text: `come`, uz: `kelmoq` },
    { text: `cook`, uz: `oshpaz, taom tayyorlamoq` },
    { text: `central`, uz: `markaziy, markazdagi` },
    { text: `city`, uz: `katta shahar` },
    { text: `centre`, uz: `markaz` },
    { text: `do`, uz: `qilmoq` },
    { text: `dinner`, uz: `kechki ovqat` },
    { text: `dance`, uz: `raqs, o'yin` },
    { text: `eat`, uz: `yemoq` },
    { text: `foot`, uz: `oyoq, oyoq kafti` },
    { text: `floor`, uz: `pol, qavat, etaj` },
    { text: `go`, uz: `yurish` },
    { text: `homework`, uz: `uyga vazifa` },
    { text: `happening`, uz: `voqea, hodisa` },
    { text: `have`, uz: `ega bo'lmoq` },
    { text: `holiday`, uz: `bayram, dam olish kuni` },
    { text: `hat`, uz: `shlapa, bosh kiyim` },
    { text: `hair`, uz: `soch, sochlar` },
    { text: `kitchen`, uz: `oshxona, o'choq boshi` },
    { text: `listen`, uz: `eshitmoq` },
    { text: `later`, uz: `keyingi` },
    { text: `lie`, uz: `yolg'on, aldamoq, aldayapti` },
    { text: `laugh`, uz: `kulgu, kulish` },
    { text: `letter`, uz: `hat, maktub` },
    { text: `learn`, uz: `o'rganmoq, saboq olmoq` },
    { text: `me`, uz: `meni, menga` },
    { text: `moment`, uz: `lag'za, fursat, payt` },
    { text: `newspaper`, uz: `gazeta` },
    { text: `off`, uz: `uzoq, o'chirilgan` },
    { text: `oh`, uz: `e, ey` },
    { text: `present`, uz: `hozir` },
    { text: `phone`, uz: `telefon` },
    { text: `park`, uz: `istirohat bog'i, taksi turargoh joyi` },
    { text: `piano`, uz: `fortepyana, pianino` },
    { text: `quiet`, uz: `tinchlik` },
    { text: `running`, uz: `yugurish` },
    { text: `read`, uz: `o'qimoq` },
    { text: `rain`, uz: `yomg'ir` },
    { text: `ring`, uz: `jaranlagan ovoz` },
    { text: `run`, uz: `yugurish` },
    { text: `river`, uz: `daryo, soy, anhor` },
    { text: `shining`, uz: `yarqiramoq` },
    { text: `something`, uz: `nimadir, qandaydir, bir narsa, biror narsa` },
    { text: `spelling`, uz: `imlo, yozish qoidasi` },
    { text: `sit`, uz: `o'tirmoq` },
    { text: `swim`, uz: `suzish` },
    { text: `stand`, uz: `tirgak, ustun` },
    { text: `stay`, uz: `bo'lish, turish, to'xtash, to'xtab` },
    { text: `sorry`, uz: `hafa bo'lgan, uzur` },
    { text: `somebody`, uz: `kimdir, birov, allakim` },
    { text: `shower`, uz: `jala, sharros yomg'ir, dush` },
    { text: `snow`, uz: `qorli` },
    { text: `sun`, uz: `quyosh` },
    { text: `shine`, uz: `yarqiramoq, nur sochmoq` },
    { text: `their`, uz: `ularning (ularga tegishli)` },
    { text: `television`, uz: `televideniya, televizor` },
    { text: `turn`, uz: `buramoq, burmoq` },
    { text: `verb`, uz: `fe'l` },
    { text: `walk`, uz: `yurish` },
    { text: `watch`, uz: `soat, kuzatuv ` },
    { text: `wear`, uz: `kiymoq` },
    { text: `wait`, uz: `kutish` },
    { text: `wash`, uz: `yuvmoq` },
]